version: '3.8'
services:
  ws-portfolio:
    build: .
    container_name: ws-portfolio-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - stack.env
      - ${ENV_FILE:-.env.local}
