name: Deploy React website

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Deploy to IIS
      uses: webfactory/ssh-agent@v0.5.0
      with: 
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      
    - name: Copy files via SSH 
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        source: "build/"
        target: "/inetpub/wwwroot/myapp"